#
# https://github.com/P3TERX/IBM-CF-V2
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: IBM Cloud Foundry - XRay

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 128M

on:
  workflow_dispatch:
  repository_dispatch:
#  schedule:
#    - cron: 0 21 * * 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME }}
      IBM_DL_XR: ${{ secrets.IBM_DL_XR }}
      IBM_DL_TR: ${{ secrets.IBM_DL_TR }}
      XR_UUID: ${{ secrets.XR_UUID }}
      XR_WS_PATH_VMESS: ${{ secrets.XR_WS_PATH_VMESS }}
      XR_WS_PATH_VLESS: ${{ secrets.XR_WS_PATH_VLESS }}
      XR_WS_PATH_TR: ${{ secrets.XR_WS_PATH_TR }}

    steps:

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zxC /tmp
        sudo install -m 755 /tmp/cf7 /usr/local/bin/cf
        cf version

    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${IBM_CF_API}" \
          -u "${IBM_CF_USERNAME}" \
          -p "${IBM_CF_PASSWORD}" \
          -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
          -s "${IBM_CF_SPACE_NAME:-dev}"

    - name: Download Latest Trojan-Go
      if: ${{ env.IBM_DL_TR }}
      run: |
        DOWNLOAD_URL="https://github.com/p4gefau1t/trojan-go/releases/latest/download/trojan-go-linux-amd64.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "latest-trojan.zip"
        unzip latest-trojan.zip trojan-go geoip.dat geosite.dat
        rm latest-trojan.zip
        chmod -v 755 trojan-go
        ./trojan-go -version
        mv trojan-go ${IBM_CF_APP_NAME}

    - name: Download Latest XRay
      if: ${{ env.IBM_DL_XR }}
      run: |
        DOWNLOAD_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "latest-xray.zip"
        unzip latest-xray.zip xray geoip.dat geosite.dat
        rm latest-xray.zip
        chmod -v 755 x*
        ./xray -version
        mv xray ${IBM_CF_APP_NAME}

    - name: Generate XRay Config File (VMess)
      if: ${{ env.XR_WS_PATH_VMESS }}
      run: |
        DOWNLOAD_URL="https://raw.githubusercontent.com/Dimitri2020007/IBM-CF-XR/main/config_vmess.json"
        curl -fsSL "$DOWNLOAD_URL" -o "vmess.json"
        base64 vmess.json > config

    - name: Generate XRay Config File (VLESS)
      if: ${{ env.XR_WS_PATH_VLESS }}
      run: |
        DOWNLOAD_URL="https://raw.githubusercontent.com/Dimitri2020007/IBM-CF-XR/main/config_vless.json"
        curl -fsSL "$DOWNLOAD_URL" -o "vless.json"
        base64 vless.json > config

    - name: Generate Trojan Config File (Trojan)
      if: ${{ env.XR_WS_PATH_TR }}
      run: |
        DOWNLOAD_URL="https://raw.githubusercontent.com/Dimitri2020007/IBM-CF-XR/main/config_trojan.json"
        curl -fsSL "$DOWNLOAD_URL" -o "trojan.json"
        base64 trojan.json > config

    - name: Generate Manifest File
      run: |
        cat << P3TERX > manifest.yml
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          random-route: true
          command: base64 -d config > config.json; ./${IBM_CF_APP_NAME} -config=config.json
          buildpacks:
          - binary_buildpack
        P3TERX

    - name: Deploy Cloud Foundry App
      run: cf push
